version: '3'
services:
  web:
    image: docker-auth-server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/auth-server
    links:
      - mongodb:mongo
  mongodb:
    image: mongo:4.0.9
    restart: always
    ports:
      - "27017:27017"
      
