version: '3'
services:
  web:
    image: docker-auth-server
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./web-site:/usr/src/app/web-site
      - ./node_modules:/usr/src/app/node_modules
    links:
      - mongodb:mongo
  mongodb:
    image: mongo:4.0.9
    restart: always
    ports:
      - "27017:27017"